# Numpy

In [1]:
import numpy as np

## Creating Arrays

In [2]:
a = np.array((1, 2, 3))
b = np.array([(1.5, 2, 3), [4, 5, 6]], dtype=float)
c = np.array([[[1.5, 2, 3], [4, 5, 6]], [[3, 2, 1], [4, 5, 6]]], dtype=float)
a, b, c

(array([1, 2, 3]),
 array([[1.5, 2. , 3. ],
        [4. , 5. , 6. ]]),
 array([[[1.5, 2. , 3. ],
         [4. , 5. , 6. ]],
 
        [[3. , 2. , 1. ],
         [4. , 5. , 6. ]]]))

In [3]:
a[0] = 10
a

array([10,  2,  3])

In [4]:
zero = np.zeros([3, 4]) #np.zeros((3, 4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((2,3,4),dtype=np.int16) #Create an array of ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [6]:
d = np.arange(10,25,2) #Create an array of evenly spaced values (step value)
d, type(d.dtype)

(array([10, 12, 14, 16, 18, 20, 22, 24]), numpy.dtype[int64])

In [7]:
np.linspace(0,2,9) #Create an array of evenlyspaced values (number of samples)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [8]:
np.full((2,2),7) #Create a constant array

array([[7, 7],
       [7, 7]])

In [9]:
i = np.eye(2) #Create a 2X2 identity matrix
r = np.random.random((2,2)) #Create an array with random values
e = np.empty((3,2), dtype=int) #Create an empty array unpredictable entries
i, r, e

(array([[1., 0.],
        [0., 1.]]),
 array([[0.29269211, 0.72267923],
        [0.52633183, 0.53105491]]),
 array([[4609434218613702656, 4611686018427387904],
        [4613937818241073152, 4616189618054758400],
        [4617315517961601024, 4618441417868443648]]))

## I/O

### Saving & Loading on Disk

In [10]:
np.save('my_array' , a)
np.savez( 'array.npz', a, b)
np.load( 'my_array.npy')

array([10,  2,  3])

### Saving & Loading Text Files 

In [22]:
tx =np.loadtxt("myfile.txt")
gft = np.genfromtxt("testCSV.csv", delimiter= ',', dtype=int)
np.savetxt( "myarray.txt", tx, delimiter= " ")
tx, gft

(array([20., 30., 40.]),
 array([[-1,  2],
        [ 2,  3],
        [ 3,  4]]))

In [23]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


### Inspecting Your Array 


In [45]:
a.shape #Array dimensions
len(a) #Length of array
b.ndim #Number of array dimensions
a.size #Number of array elements
b.dtype  #Data type of array elements
b.dtype.name  #Name of data type
b.astype(int) #Convert an array to a different type

array([1, 1, 1])

In [26]:
np.int64 #Signed 64-bit integer types
np.float32 #Standard double-precision floating point
np.complex #Complex numbers represented by 128 floats
np.bool  #Boolean type storing TRUE and FALSE values
np.object #Python object type
np.string_ #Fixed-length string type
np.unicode_ #Fixed-length unicode type

/tmp/ipykernel_1864231/2847011772.py:3: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.complex #Complex numbers represented by 128 floats
/tmp/ipykernel_1864231/2847011772.py:4: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool  #Boolean type storing TRUE and FALSE values
/tmp/ipykernel_1864231/2847011772.py:5: DeprecationWarnin

numpy.str_

## Array Mathematics 

### Arithmetic Operations 

In [32]:
a = np.zeros(3)
b = np.ones(4)
try:
    a - b
except Exception as e: 
    print(e)

operands could not be broadcast together with shapes (3,) (4,) 


In [35]:
b = np.ones(3)
a-b, np.subtract(a, b)

(array([-1., -1., -1.]), array([-1., -1., -1.]))

In [36]:
a+b, np.add(a, b)

(array([1., 1., 1.]), array([1., 1., 1.]))

In [41]:
try:
    b/a
except Exception as e:
    print(e)

/tmp/ipykernel_1864231/2280118754.py:2: RuntimeWarning: divide by zero encountered in divide
  b/a


In [47]:
a/b, np.divide(a, b), np.divide(b, a)

/tmp/ipykernel_1864231/3661671955.py:1: RuntimeWarning: divide by zero encountered in divide
  a/b, np.divide(a, b), np.divide(b, a)


(array([0., 0., 0.]), array([0., 0., 0.]), array([inf, inf, inf]))

In [48]:
a*b, np.multiply(a, b)

(array([0., 0., 0.]), array([0., 0., 0.]))

In [49]:
np.multiply(a,b) #Multiplication 
np.exp(b) #Exponentiation
np.sqrt(b) #Square root
np.sin(a)  #Print sines of an array
np.cos(b) #Elementwise cosine
np.log(a)#Elementwise natural logarithm
e.dot(f) #Dot product 

/tmp/ipykernel_1864231/3016148894.py:6: RuntimeWarning: divide by zero encountered in log
  np.log(a)#Elementwise natural logarithm


NameError: name 'e' is not defined